---
deployment:
  tasks:
    - export DEPLOYPATH=/home/menumone/public_html/git-demo/
    - /bin/cp -r ../dist/menu-demo/* $DEPLOYPATH
    - cd $DEPLOYPATH
    - /opt/cpanel/ea-nodejs16/bin/npm install
    - /opt/cpanel/ea-nodejs16/bin/npm run build -- --prod --base-href /demo/
    - rsync -av --delete ../dist/menu-demo/ $DEPLOYPATH
