---
deployment:
  tasks:
    - export DEPLOYPATH=/home/menumone/public_html/git-demo/
    - export DIST_DIR=/../dist/menu-demo
    - /bin/cp -R DIST_DIR $DEPLOYPATH
    - /opt/cpanel/ea-nodejs16/bin/npm install --prefix $DEPLOYMENT_SOURCE
    - /opt/cpanel/ea-nodejs16/bin/npm run build --prefix $DEPLOYMENT_SOURCE -- --prod --base-href /demo/
    - rsync -av --delete $DEPLOYMENT_SOURCE/dist/menu-demo/ /home/menumone/public_html/git-demo/
