---
deployment:
  tasks:
    - export DEPLOYMENT_SOURCE=/home/menumone/public_html/git-demo/
    - export DIST_DIR=$DEPLOYMENT_SOURCE/../dist/menu-demo
    - /opt/cpanel/ea-nodejs16/bin/npm install --prefix $DEPLOYMENT_SOURCE
    - /opt/cpanel/ea-nodejs16/bin/npm run build --prefix $DEPLOYMENT_SOURCE -- --prod --base-href /demo/
    - rsync -av --delete $DIST_DIR/ /home/menumone/public_html/git-demo/
