---
deployment:
  tasks:
    - export DEPLOYPATH=/home/menumone/public_html/git-demo
      - cd $DEPLOYMENT_SOURCE
      - /opt/cpanel/ea-nodejs16/bin/npm install
      - /opt/cpanel/ea-nodejs16/bin/npm run build -- --prod --base-href /demo/
      - cp -r dist/menu-demo/* /home/menumone/public_html/git-demo/
